### ISSUE TITLE
How to log request and response body's?

### ISSUE THREAD

**Issue by balexandre** [serganus/mongo-morgan-ext#1]
I would like to also save the body of the `POST` request as well when the response is sent, save what was sent...

How can I do such thing? All my attempts are not working :(

**Comment by serganus** [comment]
I have added a field in a branch version to catch `req.body` objects in case of HTTP method is POST.

Try as follows:

- `git clone -b Saving-body-objects https://github.com/serganus/mongo-morgan-ext.git`, save this to `node_modules` folder and simply delete the other vesion before doing this.
- In your code, do as follows

```
var logger = require('mongo-morgan-ext');
var db = 'mongodb://localhost:27017/MyDB';
var collection = 'Logs'
var skipfunction = function(req, res) {
return res.statusCode > 399;
} //Thiw would skip if HTTP request response is less than 399 i.e no errors.

app.use(logger(db,collection,skipfunction)); //In your express-application
```
Now you should be able to see a new field `REQUEST->body`.
